name: TranscEndence

author: sfiguz7

description: A generic Slimefun4-Addon

main: me.sfiguz7.transcendence.TranscEndence

website: https://github.com/Sfiguz7/TranscEndence

depend: [Slimefun]

version: ${project.version}

api-version: 1.14
