name: TranscEndencePlugin

author: sfiguz7

description: A generic Slimefun4-Addon

main: me.sfiguz7.transcendence.TranscEndencePlugin

website: https://github.com/Sfiguz7/TranscEndencePlugin

depend: [Slimefun]

version: ${project.version}

api-version: 1.14
