name: TranscEndencePlugin
version: ${project.version}
author: sfiguz7
description: A Slimefun4 Addon for more End content
website: https://github.com/Sfiguz7/TranscEndencePlugin

main: me.sfiguz7.transcendence.TranscEndencePlugin
depend: [Slimefun]

api-version: 1.14

commands:
  transcendence:
    description: basic TranscEndence command
    aliases: te
    usage: You either forgot to install CS-CoreLib or you installed an unsupported version.
